// Korean for the essay — English on the left, Korean on the right.
const ko: Record<string, string> = {
  'Prompt: Discuss an accomplishment, event, or realization that sparked a period of personal growth and a new understanding of yourself or others.':
    '주제: 개인적인 성장과 자신 또는 타인에 대한 새로운 이해를 이끌어 낸 성취, 사건, 혹은 깨달음에 대해 서술하시오.',
  "In August 2022, I stood alone at Incheon International Airport, poised to board a flight to Canada. It was a leap into the unknown. As the plane climbed, Neil Armstrong's words resonated in my brain: \"That's one small step for a man, one giant leap for mankind.\" For me, this flight symbolized more than just changing my address. It was a transforming start, an opportunity to grow and reshape my future.":
    '2022년 8월, 저는 인천국제공항에 혼자 서서 캐나다행 비행기에 오를 준비를 하고 있었습니다. 미지의 세계로 뛰어드는 순간이었습니다. 비행기가 이륙하자 닐 암스트롱의 말이 머릿속에 울렸습니다. "이것은 한 사람에게는 작은 발걸음이지만, 인류에게는 거대한 도약이다." 저에게 이 비행은 단순히 주소를 바꾸는 일이 아니었습니다. 성장하고 미래를 다시 그릴 기회, 변화의 출발점이었습니다.',
  "My first few days in Canada were a whirlwind of challenges. Taking classes in a foreign language, adjusting to new cultures, and living independently challenged me in ways I never imagined. Despite this whirlwind, I saw an opportunity to stretch beyond my comfort zone and get closer to my goals. Being an entrepreneur in a global marketplace, a vision I've long had, necessitated resilience and leadership. When I joined Unity 4 Charity (U4C), a non-profit that supports climate refugees and Indigenous communities, I recognized an opportunity to cultivate these traits.":
    '캐나다에서의 첫 며칠은 도전의 연속이었습니다. 낯선 언어로 수업을 듣고, 새로운 문화에 적응하고, 혼자 생활하는 일은 상상하지 못했던 방식으로 저를 시험했습니다. 그 소용돌이 속에서도 저는 안전지대를 벗어나 목표에 한 걸음 다가설 기회를 보았습니다. 오랫동안 품어 온 꿈, 글로벌 시장에서 활동하는 창업가가 되려면 회복력과 리더십이 필요했습니다. 기후 난민과 원주민 공동체를 돕는 비영리 단체 Unity 4 Charity(U4C)에 합류했을 때, 저는 그 자질을 기를 기회를 알아보았습니다.',
  'At the time, U4C was bursting with enthusiasm but lacked structure. Meetings floundered without a clear direction, roles were unclear, and progress was slow. Where others saw chaos, I saw possibilities. I set out on the ambitious mission of converting the organization into an efficient, goal-driven institution fuelled by my optimism.':
    '당시 U4C는 열정은 넘쳤지만 체계가 없었습니다. 회의는 방향 없이 흔들렸고, 역할은 불분명했으며, 진행은 더뎠습니다. 다른 사람들이 혼란을 볼 때 저는 가능성을 보았습니다. 낙관을 동력 삼아, 이 단체를 효율적이고 목표 중심적인 조직으로 바꾸겠다는 야심 찬 과제에 나섰습니다.',
  'I began by examining the personnel management systems of global leaders such as Apple and Amazon, which prompted a thorough structural redesign. U4C was reorganized into four departments: planning and development, communications and media, operations and administration, and volunteer services. Each department was assigned specific duties that were unified by the goal of obtaining official non-profit certification. Over several months, I interviewed 40 members to determine their skills and placed them in places where they could thrive.':
    'Apple과 Amazon 같은 글로벌 기업의 인사 관리 체계를 살펴보는 것에서 시작했고, 그 결과 조직 구조를 근본부터 다시 설계하게 되었습니다. U4C는 기획·개발, 홍보·미디어, 운영·행정, 봉사 서비스의 네 부서로 재편되었습니다. 각 부서에는 구체적인 임무를 맡기되, 공식 비영리 인증을 받는다는 하나의 목표로 묶었습니다. 몇 달에 걸쳐 회원 40명을 면담해 각자의 역량을 파악하고, 가장 잘 성장할 수 있는 자리에 배치했습니다.',
  "Our first significant challenge took the form of a fundraising effort. Each department met weekly to prepare: the Planning team researched and designed things to sell, Communications created engaging promotional materials, Operations secured event sites, and Volunteer Service trained members to interact with the public. The campaign's success exceeded all expectations, paving the way for future efforts. U4C acquired non-profit status in British Columbia in November 2023, demonstrating all members' commitment.":
    '첫 번째 큰 도전은 모금 활동이었습니다. 부서마다 매주 모여 준비했습니다. 기획팀은 판매할 물품을 조사하고 디자인했고, 홍보팀은 눈길을 끄는 홍보물을 만들었으며, 운영팀은 행사 장소를 확보했고, 봉사팀은 회원들이 시민과 소통하도록 교육했습니다. 캠페인은 모든 기대를 뛰어넘는 성과를 거두며 이후 활동의 길을 열었습니다. U4C는 2023년 11월 브리티시컬럼비아주 비영리 단체 지위를 얻었고, 이는 모든 회원의 헌신을 보여 주는 결과였습니다.',
  'This adventure showed me that leadership is about empowerment, not control. Leadership brings people together under a shared vision, creating an atmosphere to ignite innovation. However, the most important lesson was not about systems or strategies; resilience is the ability to turn setbacks into opportunities and persevere toward a goal.':
    '이 여정은 리더십이 통제가 아니라 힘을 실어 주는 일임을 가르쳐 주었습니다. 리더십은 사람들을 하나의 비전 아래 모으고, 혁신의 불씨를 지피는 분위기를 만듭니다. 그러나 가장 중요한 교훈은 체계나 전략이 아니었습니다. 회복력이란 좌절을 기회로 바꾸고 목표를 향해 끝까지 나아가는 힘이라는 것이었습니다.',
  'Throughout the campaign, we encountered obstacles that tested us. Creative solutions were needed to capture public interest, and moments of discord required careful mediation to align perspectives. These problems served as growth opportunities for both me and the organization. I learned how to navigate the complexities of team interactions while remaining focused on the broader picture.':
    '캠페인 내내 우리를 시험하는 장애물이 있었습니다. 시민의 관심을 끌려면 창의적인 해법이 필요했고, 의견이 부딪히는 순간에는 관점을 맞추기 위한 신중한 중재가 필요했습니다. 이런 문제들은 저와 단체 모두에게 성장의 기회가 되었습니다. 큰 그림에 집중하면서도 팀 안의 복잡한 관계를 헤쳐 나가는 법을 배웠습니다.',
  'The experience with U4C was revolutionary. It taught me the value of collaboration and balancing individual potential with a larger objective. Designing systems to increase organizational efficiency while nurturing passion and creativity became a pillar of my leadership. Furthermore, I gained the confidence to lead in uncertain, high-pressure situations.':
    'U4C에서의 경험은 저를 완전히 바꾸어 놓았습니다. 협업의 가치와, 개인의 잠재력을 더 큰 목표와 조화시키는 법을 배웠습니다. 열정과 창의성을 북돋우면서도 조직의 효율을 높이는 체계를 설계하는 일은 제 리더십의 기둥이 되었습니다. 또한 불확실하고 압박이 큰 상황에서도 이끌 수 있다는 자신감을 얻었습니다.',
  'Reflecting on this voyage, I reimagined how uncertain I felt as I boarded that plane to Canada. Back then, I feared the unknown, unsure of my readiness. But now I realize that challenges are not obstacles; they are opportunities to improve. Failures do not mark the end; rather, they serve as stepping stones to achievement. Each tiny action performed with intent builds the basis for something greater.':
    '이 여정을 돌아보며, 캐나다행 비행기에 오르던 때의 불안했던 마음을 다시 떠올렸습니다. 그때는 준비가 되었는지 확신하지 못한 채 미지의 것을 두려워했습니다. 하지만 이제는 압니다. 도전은 장애물이 아니라 더 나아질 기회이고, 실패는 끝이 아니라 성취로 가는 디딤돌입니다. 의도를 갖고 행한 작은 행동 하나하나가 더 큰 무언가의 토대가 됩니다.',
  'As I prepare to embark on the next stage in college, I carry the lessons learned from this experience. The fortitude to face uncertainty, the ingenuity to solve difficulties, and the determination to bring people together behind a common vision will guide me. Just as that flight to Canada marked the beginning, I am ready to take another leap, understanding that the journey begins with a single step.':
    '대학이라는 다음 단계를 준비하면서, 저는 이 경험에서 얻은 교훈을 안고 갑니다. 불확실함을 마주하는 용기, 어려움을 풀어내는 창의력, 사람들을 하나의 비전 뒤에 모으는 결단력이 저를 이끌 것입니다. 캐나다행 비행이 시작이었듯, 여정은 한 걸음에서 시작된다는 것을 알기에 저는 또 한 번의 도약을 준비하고 있습니다.',
};

export default ko;
