// Korean for the UTKESA page — the prose; headings stay English. English on the left, Korean on the right.
const ko: Record<string, string> = {
  "UTKESA, the University of Toronto Korean Engineering Students' Association, connects Korean engineering students through academic support, professional development, and social events. I joined the Event Department as an intern in September 2025 and became an executive in January 2026, helping plan and run the association's events. The one I care about most was a donation the association made to a museum campaign.": "토론토 대학교 한인 공학 학생회(UTKESA)는 학업 지원, 커리어 개발, 친목 행사로 한인 공학도들을 잇는 단체입니다. 저는 2025년 9월 행사부 인턴으로 들어가 2026년 1월 임원이 되었고, 학생회의 행사를 기획하고 운영하는 일을 돕고 있습니다. 그중 제가 가장 아끼는 일은 학생회가 한 박물관 캠페인에 한 기부입니다.",
  "The Royal Ontario Museum holds Canada's only permanent Gallery of Korea, and it was at risk. Without a dedicated curator, the gallery faced the possibility of closure or being folded into a broader East Asian gallery, which would blur the specific history it exists to tell. The Korea Root Initiative started a campaign to fund a permanent curator, and UTKESA chose to stand behind it.": "로열 온타리오 박물관(ROM)에는 캐나다 유일의 상설 한국관이 있는데, 그 한국관이 위기에 놓였습니다. 전담 큐레이터가 없으면 폐관되거나 더 넓은 동아시아관에 흡수될 수 있었고, 그러면 한국관이 전하기 위해 존재하는 고유한 역사가 흐려질 터였습니다. Korea Root Initiative가 상임 큐레이터 기금 캠페인을 시작했고, UTKESA는 그 뒤에 서기로 했습니다.",
  "The timing was deliberate. The association made its donation around Samil-jeol, the March 1st holiday that commemorates the 1919 Korean independence movement. For a group of Korean students studying abroad, donating around that day was our way of marking it. The funds had been raised across the year by the executive team, and the contribution went to the Korea Root Initiative in support of the curator campaign for the Gallery of Korea.": "시기는 의도한 것이었습니다. 학생회는 1919년 독립운동을 기리는 삼일절 무렵에 기부했습니다. 해외에서 공부하는 한인 학생들에게 그날 즈음 기부하는 것은 그날을 기념하는 우리 나름의 방식이었습니다. 기금은 임원진이 한 해 동안 모은 것이었고, 기부금은 한국관 큐레이터 캠페인을 지원하는 Korea Root Initiative에 전달되었습니다.",
  "The Korea Root Initiative later hosted a gathering where community leaders, organizations, and student groups came together for the cause, and that is where the contribution was handed over in person and recognized. UTKESA attended to show its support, with our 43rd president Jihan Kang and 44th president Leo Choung representing the association. As part of the event team, I helped with the work behind it. The photos below are from that day, at the fundraiser and at the gallery itself.": "이후 Korea Root Initiative는 지역 사회 지도자와 단체, 학생 모임이 이 취지로 모이는 자리를 열었고, 그곳에서 기부금이 직접 전달되고 인정받았습니다. UTKESA는 지지를 보이기 위해 참석했고, 43대 회장 강지한과 44대 회장 Leo Choung이 학생회를 대표했습니다. 행사팀의 일원으로서 저는 그 뒤의 일을 도왔습니다. 아래 사진은 그날 모금 행사와 한국관에서 찍은 것입니다.",
  "The Korea Root Initiative event and the Gallery of Korea": "Korea Root Initiative 행사와 한국관",
  "The Korea Root Initiative recognized the contribution with a certificate: CAD $400 from the Korean Engineering Students' Association at the University of Toronto, toward establishing a permanent curator for the Gallery of Korea at the ROM. It is a small amount against what a curator costs, but it is real and on the record, and it went to a specific gallery.": "Korea Root Initiative는 기부를 인증서로 인정했습니다. 토론토 대학교 한인 공학 학생회가 ROM 한국관 상임 큐레이터 설립을 위해 기부한 400 캐나다달러입니다. 큐레이터 한 명에 드는 비용에 비하면 작은 금액이지만, 실제로 기록에 남은 기부이고 특정한 전시관을 향한 것입니다.",
  "The Korea Root Initiative Certification of Contribution: presented to the Korean Engineering Students' Association at the University of Toronto for a CAD $400 contribution toward establishing a permanent curator for the Gallery of Korea at the Royal Ontario Museum, dated May 10, 2026.": "Korea Root Initiative 기부 인증서. 로열 온타리오 박물관 한국관 상임 큐레이터 설립을 위한 400 캐나다달러 기부에 대해 토론토 대학교 한인 공학 학생회에 수여, 2026년 5월 10일 자.",
  "The certificate of contribution — CAD $400, dated May 10, 2026.": "기부 인증서 — 400 캐나다달러, 2026년 5월 10일.",
  "Most of what a student association does is logistics: rooms, sign-ups, schedules. This was the part that reminded me why the logistics are worth doing. A club lets a group put a bit of money and effort toward something it decides matters, and for us that was the Gallery of Korea. The money came from events the executive team ran all year, which is a large part of why the logistics matter to me.": "학생회가 하는 일의 대부분은 실무입니다. 장소, 신청, 일정. 이 일은 그 실무가 왜 할 만한 가치가 있는지 떠올리게 해 주었습니다. 동아리는 한 무리의 사람들이 스스로 중요하다고 정한 일에 약간의 돈과 노력을 보탤 수 있게 하고, 우리에게 그것은 한국관이었습니다. 그 돈은 임원진이 한 해 내내 연 행사에서 나왔고, 그것이 제게 실무가 중요한 큰 이유입니다.",
};

export default ko;
